{% set name = "pyclustering" %}
{% set version = "0.9.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/annoviko/{{ name }}/archive/{{ version }}.tar.gz"
  sha256: affe4b2bde2765afc663b9d7af6ff0d668c66cc334d62679f4b6df9d68aa0aaa

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py<35]]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    
  host:
    - pip
    - python
  
  run:
    - matplotlib
    - numpy
    - pillow
    - python
    - scipy

test:
  imports:
    - pyclustering
    - pyclustering.cluster
    - pyclustering.cluster.examples
    - pyclustering.cluster.tests
    - pyclustering.cluster.tests.integration
    - pyclustering.cluster.tests.unit
    - pyclustering.container
    - pyclustering.container.examples
    - pyclustering.container.tests
    - pyclustering.container.tests.unit
    - pyclustering.core
    - pyclustering.core.tests
    - pyclustering.gcolor
    - pyclustering.gcolor.examples
    - pyclustering.gcolor.tests
    - pyclustering.nnet
    - pyclustering.nnet.examples
    - pyclustering.nnet.tests
    - pyclustering.nnet.tests.integration
    - pyclustering.nnet.tests.unit
    - pyclustering.samples
    - pyclustering.tests
    - pyclustering.utils
    - pyclustering.utils.examples
    - pyclustering.utils.tests
    - pyclustering.utils.tests.integration
    - pyclustering.utils.tests.unit

about:
  home: "https://github.com/annoviko/pyclustering"
  license: "GNU General Public v3 (GPLv3)"
  license_family: GPL3
  license_file: LICENSE
  summary: "pyclustering is a Python data mining library based on clustering algorithms, oscillatory networks and neural networks"
  dev_url: "https://github.com/annoviko/pyclustering"

extra:
  recipe-maintainers:
    - agcopenhaver
