package:
  name: rtools
  version: 3.5.0

source:
  - url: https://cran.r-project.org/bin/windows/Rtools/Rtools35.exe
    sha256: 18fd63bb9c903e1f9bfce5c9a2600bd24213295760592dbc130b73a61e9d9414
  - url: http://constexpr.org/innoextract/files/innoextract-1.6-windows.zip                  # [win64]
    md5: e3abf26e436c8f1858e2e06a67a37b60                                                    # [win64]
    folder: innoextract                                                                      # [win64]

build:
  skip: True  # [not win]
  skip_compile_pyc:
    - '**/*.py'

requirements:
  build:
    - python-libarchive-c
    - posix  # [win]
    - m2-p7zip  # [win]
